import React, { useState, useEffect } from 'react';
import DashboardLayout from '@/components/layout/DashboardLayout';
import TableList from '@/components/dashboard/TableList';
import { Button } from '@/components/ui/button';
import { api } from '@/lib/api';
import { useUser } from '@/contexts/UserContext';
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { Form, FormField, FormItem, FormLabel, FormControl, FormMessage } from '@/components/ui/form';
import { z } from 'zod';
import { useForm, SubmitHandler } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Input } from '@/components/ui/input';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Loader2, UserPlus, Trash2, Pencil } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

// Define types for reference data
interface Program {
  id: string;
  name: string;
  level: string;
  duration: number;
}

interface Nationality {
  id: string;
  name: string;
}

// Define student type with all required fields
interface Student {
  id: string;
  firstName: string;
  lastName: string;
  personalEmail: string;
  gender: string;
  dateOfBirth: string;
  yearOfStudy: number;
  programId: string;
  nationalityId: string;
  studentNumber?: string; // Generated by backend
  universityEmail?: string; // Generated by backend
  line1: string;
  line2?: string;
  city: string;
  state?: string;
  postalCode: string;
  country: string;
  kinName: string;
  kinRelation: string;
  kinPhone: string;
  role: string;
}

// Define a validation schema for student data with all fields required by backend
const studentFormSchema = z.object({
  firstName: z.string().min(1, "Required"),
  lastName: z.string().min(1, "Required"),
  personalEmail: z.string().email("Invalid email"),
  gender: z.enum(['male', 'female', 'other', 'prefer_not_to_say']),
  dateOfBirth: z.string().refine(d => !isNaN(Date.parse(d)), "Invalid date"),
  yearOfStudy: z.coerce.number().int().min(1).max(7),
  programId: z.string().min(1, "Required"),
  nationalityId: z.string().min(1, "Required"),
  // Address fields
  line1: z.string().min(1, "Required"),
  line2: z.string().optional(),
  city: z.string().min(1, "Required"),
  state: z.string().optional(),
  postalCode: z.string().min(1, "Required"),
  country: z.string().min(1, "Required"),
  // Next of kin fields
  kinName: z.string().min(1, "Required"),
  kinRelation: z.string().min(1, "Required"),
  kinPhone: z.string().min(1, "Required"),
});

type StudentFormValues = z.infer<typeof studentFormSchema>;

const ManageStudents: React.FC = () => {
  const { toast } = useToast();
  const { activeDepartment } = useUser();
  const deptCode = activeDepartment?.departmentCode!;
  const [students, setStudents] = useState<Student[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [selectedStudent, setSelectedStudent] = useState<Student | null>(null);

  // fetch students
  useEffect(() => {
    if (!deptCode) return;
    setIsLoading(true);
    
    // Use the revised endpoint for student data
    api.getDepartmentStudents(deptCode)
      .then((response: any) => {
        // Backend returns data in { users: [...] } format
        if (response && response.users && Array.isArray(response.users)) {
          setStudents(response.users);
        } else if (Array.isArray(response)) {
          setStudents(response);
        } else {
          console.error('Unexpected student data format:', response);
          toast({ 
            title: "Error", 
            description: "Received invalid student data format", 
            variant: "destructive" 
          });
          
          // Fallback to empty array
          setStudents([]);
        }
      })
      .catch((error) => {
        console.error('Error loading students:', error);
        toast({ 
          title: "Error", 
          description: "Cannot load students: " + (error.message || 'Unknown error'), 
          variant: "destructive" 
        });
        
        // Fallback to empty array
        setStudents([]);
      })
      .finally(() => setIsLoading(false));
  }, [deptCode, toast]);

  // Form for adding a new student
  const form = useForm<StudentFormValues>({
    resolver: zodResolver(studentFormSchema),
    defaultValues: {
      firstName: '', 
      lastName: '', 
      personalEmail: '', 
      gender: 'prefer_not_to_say' as const, 
      dateOfBirth: '',
      yearOfStudy: 1,
      programId: '',
      nationalityId: '',
      line1: '',
      line2: '',
      city: '',
      state: '',
      postalCode: '',
      country: '',
      kinName: '',
      kinRelation: '',
      kinPhone: ''
    }
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  
  // Load programs and nationalities
  const [programs, setPrograms] = useState<Program[]>([]);
  const [nationalities, setNationalities] = useState<Nationality[]>([]);

  // Fetch reference data (programs and nationalities)
  useEffect(() => {
    const fetchReferenceData = async () => {
      try {
        console.log('Fetching programs for department:', deptCode);
        
        // Get programs from the API
        try {
          // Get auth data from localStorage - this is how your app stores tokens
          const authJson = localStorage.getItem('auth');
          let token = '';
          
          if (authJson) {
            try {
              const authData = JSON.parse(authJson);
              token = authData.token || '';
              console.log('Using token from auth data');
            } catch (e) {
              console.error('Error parsing auth data:', e);
            }
          }
          
          const response = await fetch('/api/department/programs', {
            headers: {
              'Authorization': `Bearer ${token}`,
              'Content-Type': 'application/json'
            }
          });
          console.log('API request made with auth token present:', !!token);
          
          if (response.ok) {
            const data = await response.json();
            console.log('API response for programs:', data);
            
            if (data && data.programs && Array.isArray(data.programs)) {
              console.log('Successfully loaded programs:', data.programs);
              setPrograms(data.programs);
            } else {
              console.warn('Unexpected programs data format from API:', data);
              // Fallback to placeholder data if API doesn't return expected format
              setPrograms([{ id: 'prog1', name: 'Computer Science', level: 'Undergraduate', duration: 4 }]);
            }
          } else {
            console.warn('Failed to fetch programs, status:', response.status);
            // Fallback to placeholder data
            setPrograms([{ id: 'prog1', name: 'Computer Science', level: 'Undergraduate', duration: 4 }]);
          }
        } catch (fetchError) {
          console.error('Error fetching programs:', fetchError);
          // Fallback to placeholder data
          setPrograms([{ id: 'prog1', name: 'Computer Science', level: 'Undergraduate', duration: 4 }]);
        }
        
        // For now, still using placeholder data for nationalities
        const nationalitiesData = [{ id: 'nat1', name: 'United Kingdom' }];
        setNationalities(nationalitiesData);
      } catch (error) {
        console.error('Error loading reference data:', error);
        toast({ 
          title: "Error", 
          description: "Failed to load reference data", 
          variant: "destructive" 
        });
        
        // Ensure we have fallbacks
        setPrograms([{ id: 'prog1', name: 'Computer Science', level: 'Undergraduate', duration: 4 }]);
        setNationalities([{ id: 'nat1', name: 'United Kingdom' }]);
      }
    };
    
    fetchReferenceData();
  }, [toast, deptCode]);

  const onSubmit: SubmitHandler<StudentFormValues> = async (data) => {
    setIsSubmitting(true);
    try {
      // Add required fields for the API
      const studentData = {
        ...data,
        role: 'student' as const
      };
      
      // Send student data to the backend
      const response = await api.addStudent(studentData, deptCode);
      
      // Handle the response structure returned by our backend
      const added = response.user || response;
      
      // Update the students list with the new student
      setStudents(prev => [...prev, added]);
      toast({ 
        title: "Student Added", 
        description: `${data.firstName} ${data.lastName} was successfully added.` 
      });
      
      // Close dialog and reset form
      setIsDialogOpen(false);
      form.reset();
    } catch (e: any) {
      console.error('Error adding student:', e);
      toast({ 
        title: "Error", 
        description: e.message || 'Failed to add student', 
        variant: "destructive" 
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  // Handle updating student
  const handleUpdate = async (data: StudentFormValues) => {
    if (!selectedStudent) return;
    
    setIsSubmitting(true);
    try {
      // Send updated data to the backend
      await api.updateStudent(selectedStudent.id, {
        ...data,
        role: 'student' 
      }, deptCode);
      
      // Update the students list
      setStudents(prev => prev.map(s => s.id === selectedStudent.id ? {
        ...s,
        firstName: data.firstName,
        lastName: data.lastName,
        personalEmail: data.personalEmail,
        yearOfStudy: data.yearOfStudy,
        gender: data.gender,
        dateOfBirth: data.dateOfBirth,
        programId: data.programId,
        nationalityId: data.nationalityId,
        line1: data.line1,
        line2: data.line2,
        city: data.city,
        state: data.state,
        postalCode: data.postalCode,
        country: data.country,
        kinName: data.kinName,
        kinRelation: data.kinRelation,
        kinPhone: data.kinPhone
      } : s));
      
      toast({ 
        title: "Student Updated", 
        description: `${data.firstName} ${data.lastName}'s information has been updated.` 
      });
      
      // Close dialog and reset
      setIsEditDialogOpen(false);
      setSelectedStudent(null);
      form.reset();
    } catch (e: any) {
      console.error('Error updating student:', e);
      toast({ 
        title: "Error", 
        description: e.message || 'Failed to update student', 
        variant: "destructive" 
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleDelete = async (id: string) => {
    if (!window.confirm('Are you sure you want to delete this student?')) {
      return; // User canceled the operation
    }
    
    setIsLoading(true);
    try {
      await api.deleteStudent(id, deptCode);
      
      // Refresh the student list
      setStudents(prev => prev.filter(s => s.id !== id));
      
      toast({ 
        title: "Student Deleted", 
        description: "The student has been removed from your department." 
      });
    } catch (error: any) {
      console.error('Error deleting student:', error);
      toast({ 
        title: "Error", 
        description: error.message || 'Failed to delete student', 
        variant: "destructive" 
      });
    } finally {
      setIsLoading(false);
    }
  };

  // table columns
  const columns = [
    { key:'name', header:'Name', cell:(s:Student)=><>{s.firstName} {s.lastName}</> },
    { key:'number', header:'Student#', cell:(s:Student)=><>{s.studentNumber}</> },
    { key:'year', header:'Year', cell:(s:Student)=><>{s.yearOfStudy}</> },
    { key:'email', header:'Email', cell:(s:Student)=><>{s.personalEmail}</> },
    { key:'actions', header:'Actions', cell:(s:Student)=>
      <div className="flex space-x-2">
        <Button 
          variant="ghost" 
          size="icon" 
          onClick={() => {
            // Pre-populate form with student data
            form.reset({
              firstName: s.firstName,
              lastName: s.lastName,
              personalEmail: s.personalEmail,
              gender: (s.gender as "male" | "female" | "other" | "prefer_not_to_say"),
              dateOfBirth: s.dateOfBirth,
              yearOfStudy: s.yearOfStudy,
              programId: s.programId,
              nationalityId: s.nationalityId || '',
              line1: s.line1,
              line2: s.line2 || '',
              city: s.city,
              state: s.state || '',
              postalCode: s.postalCode,
              country: s.country,
              kinName: s.kinName,
              kinRelation: s.kinRelation,
              kinPhone: s.kinPhone
            });
            setSelectedStudent(s);
            setIsEditDialogOpen(true);
          }}
        >
          <Pencil className="h-4 w-4" />
        </Button>
        <Button variant="ghost" size="icon" onClick={()=>handleDelete(s.id)}>
          <Trash2 className="h-4 w-4 text-red-600"/>
        </Button>
      </div>
    }
  ];

  return (
    <DashboardLayout>
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-2xl font-bold">Manage Students</h2>
        <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
          <DialogTrigger asChild>
            <Button><UserPlus className="mr-2"/>Add Student</Button>
          </DialogTrigger>
          <DialogContent className="max-h-[90vh] overflow-y-auto">
            <DialogHeader><DialogTitle>New Student</DialogTitle></DialogHeader>
            <Form {...form}>
              <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                {/* Personal Details Section */}
                <div className="space-y-2">
                  <h3 className="text-lg font-medium">Personal Details</h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <FormField name="firstName" control={form.control} render={({field})=>(
                      <FormItem>
                        <FormLabel>First Name</FormLabel>
                        <FormControl><Input {...field}/></FormControl>
                        <FormMessage/>
                      </FormItem>
                    )}/>
                    <FormField name="lastName" control={form.control} render={({field})=>(
                      <FormItem>
                        <FormLabel>Last Name</FormLabel>
                        <FormControl><Input {...field}/></FormControl>
                        <FormMessage/>
                      </FormItem>
                    )}/>
                  </div>
                  
                  <FormField name="personalEmail" control={form.control} render={({field})=>(
                    <FormItem>
                      <FormLabel>Personal Email</FormLabel>
                      <FormControl><Input type="email" {...field}/></FormControl>
                      <FormMessage/>
                    </FormItem>
                  )}/>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <FormField name="gender" control={form.control} render={({field})=>(
                      <FormItem>
                        <FormLabel>Gender</FormLabel>
                        <FormControl>
                          <Select onValueChange={field.onChange} defaultValue={field.value}>
                            <SelectTrigger>
                              <SelectValue placeholder="Select gender" />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem key="add-gender-male" value="male">Male</SelectItem>
                              <SelectItem key="add-gender-female" value="female">Female</SelectItem>
                              <SelectItem key="add-gender-other" value="other">Other</SelectItem>
                              <SelectItem key="add-gender-prefer" value="prefer_not_to_say">Prefer not to say</SelectItem>
                            </SelectContent>
                          </Select>
                        </FormControl>
                        <FormMessage/>
                      </FormItem>
                    )}/>
                    <FormField name="dateOfBirth" control={form.control} render={({field})=>(
                      <FormItem>
                        <FormLabel>Date of Birth</FormLabel>
                        <FormControl><Input type="date" {...field}/></FormControl>
                        <FormMessage/>
                      </FormItem>
                    )}/>
                  </div>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <FormField name="yearOfStudy" control={form.control} render={({field})=>(
                      <FormItem>
                        <FormLabel>Year of Study</FormLabel>
                        <FormControl>
                          <Select onValueChange={v=>field.onChange(Number(v))} defaultValue={String(field.value)}>
                            <SelectTrigger>
                              <SelectValue placeholder="Select year" />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem key="add-year-1" value="1">Year 1</SelectItem>
                              <SelectItem key="add-year-2" value="2">Year 2</SelectItem>
                              <SelectItem key="add-year-3" value="3">Year 3</SelectItem>
                              <SelectItem key="add-year-4" value="4">Year 4</SelectItem>
                              <SelectItem key="add-year-5" value="5">Year 5</SelectItem>
                              <SelectItem key="add-year-6" value="6">Year 6</SelectItem>
                              <SelectItem key="add-year-7" value="7">Year 7</SelectItem>
                            </SelectContent>
                          </Select>
                        </FormControl>
                        <FormMessage/>
                      </FormItem>
                    )}/>
                    <FormField name="programId" control={form.control} render={({field})=>(
                      <FormItem>
                        <FormLabel>Program</FormLabel>
                        <FormControl>
                          <Select onValueChange={field.onChange} defaultValue={field.value}>
                            <SelectTrigger>
                              <SelectValue placeholder="Select program" />
                            </SelectTrigger>
                            <SelectContent>
                              {programs.map(prog => (
                                <SelectItem key={prog.id} value={prog.id}>{prog.name}</SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </FormControl>
                        <FormMessage/>
                      </FormItem>
                    )}/>
                  </div>
                  
                  <FormField name="nationalityId" control={form.control} render={({field})=>(
                    <FormItem>
                      <FormLabel>Nationality</FormLabel>
                      <FormControl>
                        <Select onValueChange={field.onChange} defaultValue={field.value || ''}>
                          <SelectTrigger>
                            <SelectValue placeholder="Select nationality" />
                          </SelectTrigger>
                          <SelectContent>
                            {nationalities.map(nat => (
                              <SelectItem key={nat.id} value={nat.id}>{nat.name}</SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </FormControl>
                      <FormMessage/>
                    </FormItem>
                  )}/>
                </div>
                
                {/* Address Section */}
                <div className="space-y-2">
                  <h3 className="text-lg font-medium">Address</h3>
                  <FormField name="line1" control={form.control} render={({field})=>(
                    <FormItem>
                      <FormLabel>Address Line 1</FormLabel>
                      <FormControl><Input {...field}/></FormControl>
                      <FormMessage/>
                    </FormItem>
                  )}/>
                  <FormField name="line2" control={form.control} render={({field})=>(
                    <FormItem>
                      <FormLabel>Address Line 2 (Optional)</FormLabel>
                      <FormControl><Input {...field}/></FormControl>
                      <FormMessage/>
                    </FormItem>
                  )}/>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <FormField name="city" control={form.control} render={({field})=>(
                      <FormItem>
                        <FormLabel>City</FormLabel>
                        <FormControl><Input {...field}/></FormControl>
                        <FormMessage/>
                      </FormItem>
                    )}/>
                    <FormField name="state" control={form.control} render={({field})=>(
                      <FormItem>
                        <FormLabel>State/Province (Optional)</FormLabel>
                        <FormControl><Input {...field}/></FormControl>
                        <FormMessage/>
                      </FormItem>
                    )}/>
                  </div>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <FormField name="postalCode" control={form.control} render={({field})=>(
                      <FormItem>
                        <FormLabel>Postal Code</FormLabel>
                        <FormControl><Input {...field}/></FormControl>
                        <FormMessage/>
                      </FormItem>
                    )}/>
                    <FormField name="country" control={form.control} render={({field})=>(
                      <FormItem>
                        <FormLabel>Country</FormLabel>
                        <FormControl><Input {...field}/></FormControl>
                        <FormMessage/>
                      </FormItem>
                    )}/>
                  </div>
                </div>
                
                {/* Next of Kin Section */}
                <div className="space-y-2">
                  <h3 className="text-lg font-medium">Next of Kin</h3>
                  <FormField name="kinName" control={form.control} render={({field})=>(
                    <FormItem>
                      <FormLabel>Next of Kin Name</FormLabel>
                      <FormControl><Input {...field}/></FormControl>
                      <FormMessage/>
                    </FormItem>
                  )}/>
                  <FormField name="kinRelation" control={form.control} render={({field})=>(
                    <FormItem>
                      <FormLabel>Relationship</FormLabel>
                      <FormControl><Input {...field}/></FormControl>
                      <FormMessage/>
                    </FormItem>
                  )}/>
                  <FormField name="kinPhone" control={form.control} render={({field})=>(
                    <FormItem>
                      <FormLabel>Contact Phone</FormLabel>
                      <FormControl><Input {...field}/></FormControl>
                      <FormMessage/>
                    </FormItem>
                  )}/>
                </div>
                
                <DialogFooter>
                  <Button variant="outline" onClick={()=>setIsDialogOpen(false)}>Cancel</Button>
                  <Button type="submit" disabled={isSubmitting}>
                    {isSubmitting ? <Loader2 className="animate-spin mr-2"/> : <UserPlus className="mr-2"/>}
                    Add Student
                  </Button>
                </DialogFooter>
              </form>
            </Form>
          </DialogContent>
        </Dialog>
      </div>

      {/* Edit Student Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Edit Student</DialogTitle>
            <DialogDescription>
              Update student information
            </DialogDescription>
          </DialogHeader>
          
          <Form {...form}>
            <form onSubmit={form.handleSubmit(handleUpdate)} className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="firstName"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>First Name</FormLabel>
                      <FormControl>
                        <Input {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                
                <FormField
                  control={form.control}
                  name="lastName"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Last Name</FormLabel>
                      <FormControl>
                        <Input {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* University email is generated on the backend based on student name */}
                {selectedStudent && (
                  <div className="space-y-2">
                    <label className="text-sm font-medium">University Email</label>
                    <p className="text-sm text-muted-foreground">
                      {selectedStudent.universityEmail || 'Will be generated automatically'}
                    </p>
                  </div>
                )}
                
                <FormField
                  control={form.control}
                  name="personalEmail"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Personal Email (optional)</FormLabel>
                      <FormControl>
                        <Input type="email" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                
                <FormField
                  control={form.control}
                  name="yearOfStudy"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Year of Study</FormLabel>
                      <Select onValueChange={(v) => field.onChange(Number(v))} value={String(field.value)}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Select year" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem key="edit-year-1" value="1">Year 1</SelectItem>
                          <SelectItem key="edit-year-2" value="2">Year 2</SelectItem>
                          <SelectItem key="edit-year-3" value="3">Year 3</SelectItem>
                          <SelectItem key="edit-year-4" value="4">Year 4</SelectItem>
                          <SelectItem key="edit-year-5" value="5">Year 5</SelectItem>
                          <SelectItem key="edit-year-6" value="6">Year 6</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="gender"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Gender</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Select gender" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem key="edit-gender-male" value="male">Male</SelectItem>
                          <SelectItem key="edit-gender-female" value="female">Female</SelectItem>
                          <SelectItem key="edit-gender-other" value="other">Other</SelectItem>
                          <SelectItem key="edit-gender-prefer" value="prefer_not_to_say">Prefer not to say</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                
                <FormField
                  control={form.control}
                  name="dateOfBirth"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Date of Birth</FormLabel>
                      <FormControl>
                        <Input type="date" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
              
              <DialogFooter>
                <Button variant="outline" onClick={() => setIsEditDialogOpen(false)}>Cancel</Button>
                <Button type="submit" disabled={isSubmitting}>
                  {isSubmitting ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Updating...
                    </>
                  ) : (
                    'Update Student'
                  )}
                </Button>
              </DialogFooter>
            </form>
          </Form>
        </DialogContent>
      </Dialog>
      
      {isLoading 
        ? <div className="py-10 text-center"><Loader2 className="animate-spin text-primary h-8 w-8"/></div>
        : <TableList columns={columns} data={students}/>
      }
    </DashboardLayout>
  );
};

export default ManageStudents;
